/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.23
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE PACKAGE
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#ifdef PACKAGE_NAME
#define CMDLINE_PARSER_PACKAGE_NAME PACKAGE_NAME
#else
#define CMDLINE_PARSER_PACKAGE_NAME PACKAGE
#endif
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION VERSION
#endif

enum enum_case { case__NULL = -1, case_arg_initial = 0, case_arg_alternating, case_arg_upper, case_arg_lower, case_arg_random, case_arg_first, case_arg_capitalize };

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * wordfile_arg;	/**< @brief Specify that the file WORDFILE contains the list of valid words from which to generate passphrases. Multiple wordfiles can be provided, separated by commas. Provided wordfiles: eff-long, eff-short, eff-special, legacy, spa-mich (Spanish), fin-kotus (Finnish), fr-freelang (French), fr-corrected.txt (French), pt-ipublicis (Portuguese), ita-wiki (Italian), ger-anlx (German), eff_large_de_sample.wordlist (German), nor-nb (Norwegian) (default='eff-long').  */
  char * wordfile_orig;	/**< @brief Specify that the file WORDFILE contains the list of valid words from which to generate passphrases. Multiple wordfiles can be provided, separated by commas. Provided wordfiles: eff-long, eff-short, eff-special, legacy, spa-mich (Spanish), fin-kotus (Finnish), fr-freelang (French), fr-corrected.txt (French), pt-ipublicis (Portuguese), ita-wiki (Italian), ger-anlx (German), eff_large_de_sample.wordlist (German), nor-nb (Norwegian) original value given at command line.  */
  const char *wordfile_help; /**< @brief Specify that the file WORDFILE contains the list of valid words from which to generate passphrases. Multiple wordfiles can be provided, separated by commas. Provided wordfiles: eff-long, eff-short, eff-special, legacy, spa-mich (Spanish), fin-kotus (Finnish), fr-freelang (French), fr-corrected.txt (French), pt-ipublicis (Portuguese), ita-wiki (Italian), ger-anlx (German), eff_large_de_sample.wordlist (German), nor-nb (Norwegian) help description.  */
  int min_arg;	/**< @brief Generate passphrases containing words with at least MIN_LENGTH characters. (default='5').  */
  char * min_orig;	/**< @brief Generate passphrases containing words with at least MIN_LENGTH characters. original value given at command line.  */
  const char *min_help; /**< @brief Generate passphrases containing words with at least MIN_LENGTH characters. help description.  */
  int max_arg;	/**< @brief Generate passphrases containing words with at most MAX_LENGTH characters. (default='9').  */
  char * max_orig;	/**< @brief Generate passphrases containing words with at most MAX_LENGTH characters. original value given at command line.  */
  const char *max_help; /**< @brief Generate passphrases containing words with at most MAX_LENGTH characters. help description.  */
  int num_words_arg;	/**< @brief Generate passphrases containing exactly NUM_WORDS words. (default='6').  */
  char * num_words_orig;	/**< @brief Generate passphrases containing exactly NUM_WORDS words. original value given at command line.  */
  const char *num_words_help; /**< @brief Generate passphrases containing exactly NUM_WORDS words. help description.  */
  char * acrostic_arg;	/**< @brief Generate passphrases with an acrostic matching ACROSTIC..  */
  char * acrostic_orig;	/**< @brief Generate passphrases with an acrostic matching ACROSTIC. original value given at command line.  */
  const char *acrostic_help; /**< @brief Generate passphrases with an acrostic matching ACROSTIC. help description.  */
  int interactive_flag;	/**< @brief Generate and output a passphrase, query the user to accept it, and loop until one is accepted. (default=off).  */
  const char *interactive_help; /**< @brief Generate and output a passphrase, query the user to accept it, and loop until one is accepted. help description.  */
  char * regex_match_arg;	/**< @brief Limit passphrases to only include words matching the regex pattern REGEX (e.g. '^[a-z]*$')..  */
  char * regex_match_orig;	/**< @brief Limit passphrases to only include words matching the regex pattern REGEX (e.g. '^[a-z]*$'). original value given at command line.  */
  const char *regex_match_help; /**< @brief Limit passphrases to only include words matching the regex pattern REGEX (e.g. '^[a-z]*$'). help description.  */
  int count_arg;	/**< @brief Generate COUNT passphrases..  */
  char * count_orig;	/**< @brief Generate COUNT passphrases. original value given at command line.  */
  const char *count_help; /**< @brief Generate COUNT passphrases. help description.  */
  char * delim_arg;	/**< @brief Separate words within a passphrase with DELIM. (default=' ').  */
  char * delim_orig;	/**< @brief Separate words within a passphrase with DELIM. original value given at command line.  */
  const char *delim_help; /**< @brief Separate words within a passphrase with DELIM. help description.  */
  int random_delimiters_flag;	/**< @brief Use randomized delimiters between words. --delimiter will be ignored (default=off).  */
  const char *random_delimiters_help; /**< @brief Use randomized delimiters between words. --delimiter will be ignored help description.  */
  char * valid_delimiters_arg;	/**< @brief A string with all valid delimiter characters. For example, '^&*' would use ^, &, or *. (default='!@#$%^&*()0123456789').  */
  char * valid_delimiters_orig;	/**< @brief A string with all valid delimiter characters. For example, '^&*' would use ^, &, or *. original value given at command line.  */
  const char *valid_delimiters_help; /**< @brief A string with all valid delimiter characters. For example, '^&*' would use ^, &, or *. help description.  */
  char * separator_arg;	/**< @brief Separate generated passphrases with SEP..  */
  char * separator_orig;	/**< @brief Separate generated passphrases with SEP. original value given at command line.  */
  const char *separator_help; /**< @brief Separate generated passphrases with SEP. help description.  */
  enum enum_case case_arg;	/**< @brief Choose the method for setting the case of each word in the passphrase. (default='initial').  */
  char * case_orig;	/**< @brief Choose the method for setting the case of each word in the passphrase. original value given at command line.  */
  const char *case_help; /**< @brief Choose the method for setting the case of each word in the passphrase. help description.  */
  int verbose_flag;	/**< @brief Report various metrics for given options and general verbose output. (default=off).  */
  const char *verbose_help; /**< @brief Report various metrics for given options and general verbose output. help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int wordfile_given ;	/**< @brief Whether wordfile was given.  */
  unsigned int min_given ;	/**< @brief Whether min was given.  */
  unsigned int max_given ;	/**< @brief Whether max was given.  */
  unsigned int num_words_given ;	/**< @brief Whether num-words was given.  */
  unsigned int acrostic_given ;	/**< @brief Whether acrostic was given.  */
  unsigned int interactive_given ;	/**< @brief Whether interactive was given.  */
  unsigned int regex_match_given ;	/**< @brief Whether regex-match was given.  */
  unsigned int count_given ;	/**< @brief Whether count was given.  */
  unsigned int delim_given ;	/**< @brief Whether delim was given.  */
  unsigned int random_delimiters_given ;	/**< @brief Whether random-delimiters was given.  */
  unsigned int valid_delimiters_given ;	/**< @brief Whether valid-delimiters was given.  */
  unsigned int separator_given ;	/**< @brief Whether separator was given.  */
  unsigned int case_given ;	/**< @brief Whether case was given.  */
  unsigned int verbose_given ;	/**< @brief Whether verbose was given.  */

} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief the description string of the program */
extern const char *gengetopt_args_info_description;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);

extern const char *cmdline_parser_case_values[];  /**< @brief Possible values for case. */


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
